### ISSUE TITLE
rtf text showing up in search results

### ISSUE THREAD

**Issue by derekeder** [datamade/nyc-council-councilmatic#104]
When searching for '[algorithm](https://laws.council.nyc.gov/search/?q=algorithm)' several results have what appear to be rtf text in their descriptions:

<img width="753" alt="screen shot 2017-12-18 at 4 48 10 pm" src="https://user-images.githubusercontent.com/919583/34131951-ac55f8b0-e445-11e7-8ec5-72d87e697357.png">

Here's a few specific examples:

* https://laws.council.nyc.gov/legislation/t-2017-7005/
* https://laws.council.nyc.gov/legislation/int-1193-2016/

**Comment by reginafcompton** [comment]
I have a fix for this in an [open PR](https://github.com/datamade/nyc-council-councilmatic/pull/116). 
After merging it, we'll need to rebuild the index.....

**Comment by reginafcompton** [comment]
RTF-free search results are now available on Councilmatic. Closing!
