### ISSUE TITLE
Bills from last session should be "Filed, End of Session"

### ISSUE THREAD

**Issue by reginafcompton** [datamade/nyc-council-councilmatic#112]
Councilmatic shows bills as "Active," though they were “filed," due to the end of the council session 

From NYC: "This is an incorrect status, can the active status be changed to Filed, End of Session? We should have no files with the status of active from the previous session."

**Comment by reginafcompton** [comment]
We facet the bills by status, as given here: https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/haystack_indexes.py#L66

For NYC, we determine the inferred status like this: https://github.com/datamade/nyc-council-councilmatic/blob/master/nyc/models.py#L79

Clearly, the `inferred_status` function does not have logic to account for the end of 2018, nor does it have a "Filed, End of Session" status. So, it looks like we need to update the `inferred_status` property in the NYC Bill model.

**Comment by reginafcompton** [comment]
Just as a reference point, here are a couple bills that should receive a status of "File, End of session":

https://laws.council.nyc.gov/legislation/res-1586-2017/
https://laws.council.nyc.gov/legislation/res-518-2014/

**Comment by jeancochrane** [comment]
We had a few follow-up questions, namely:

- How often do sessions end?
- What does "filed" mean?
- Are "filed - end of session" bills also "inactive"? Do we need more categories for "inactive" bills?

**Comment by jeancochrane** [comment]
Reopening until we deploy.
