### ISSUE TITLE
New members appear as "Vacant"

### ISSUE THREAD

**Issue by reginafcompton** [datamade/nyc-council-councilmatic#113]
Why are these members vacant? https://laws.council.nyc.gov/council-members/

**Comment by reginafcompton** [comment]
`import_data` looks for a [post](https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/management/commands/import_data.py#L862) to create [the relation between post and memberships](https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/models.py#L617)...which we need to determine the [current members of NYC Council](https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/models.py#L597).

The "vacant" people do not have a post attribute in the OCD API, e.g.:
https://ocd.datamade.us/ocd-person/2c9ad9ee-ea68-474c-a435-a20315630767/
https://ocd.datamade.us/ocd-person/db663358-3f7c-4640-a94d-6ba7d87c4c99/
https://ocd.datamade.us/ocd-person/d56d4f30-d2ab-4ab5-a67d-231261bf8e07/
https://ocd.datamade.us/ocd-person/67fde978-0adc-4f05-a372-147826a4dc48/

@hancush - can you look into this?

**Comment by hancush** [comment]
Will look into it this afternoon!

**Comment by hancush** [comment]
Looks like this was resolved by https://github.com/opencivicdata/scrapers-us-municipal/pull/199! 

The post data is now live in the OCD API, so this should be fixed next time we run `import_data`.

**Comment by reginafcompton** [comment]
Voila! https://laws.council.nyc.gov/council-members/
