### ISSUE TITLE
Tags on the search page to do not behave as expected

### ISSUE THREAD

**Issue by reginafcompton** [datamade/nyc-council-councilmatic#123]
The tags on the search page point to "topics" and "pseudo-topics": https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/templates/partials/tags.html#L20

NYC Councilmatic does not have custom logic for preparing these, as we do with Chicago and [LA Metro](https://github.com/datamade/la-metro-councilmatic/blob/master/lametro/search_indexes.py#L44).

Let's have these tags point to the controlling body, instead.

**Comment by jeancochrane** [comment]
@reginafcompton I think we can close this one thanks to #124, no?
