### ISSUE TITLE
IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "councilmatic_core_bill_slug_key"

### ISSUE THREAD

**Issue by hancush** [datamade/nyc-council-councilmatic#147]
DETAIL:  Key (slug)=(int-0969-2018) already exists.

https://sentry.io/datamade/nyc-council-councilmatic/issues/750193666/?query=is%3Aunresolved%20import_data

indeed, there are two bills in the ocd api with an identifier that would be slugified as "int-0969-2018": https://ocd.datamade.us/bills/?identifier__endswith=0969-2018

one in them is now in legistar (and the ocd api/councilmatic database) as [09**5**9-2018](https://nyc.legistar.com/LegislationDetail.aspx?ID=3518492&GUID=5E55A341-3B7F-4D8B-A74C-22906527C1ED&Options=ID|Text|&Search=prohibited+street+vending+zone).

we should delete [the erroneous 0969-2018 version](https://ocd.datamade.us/ocd-bill/1056cdbe-99a9-4ee1-942b-83b363ffb400/) from the ocd api. (it was never imported to councilmatic because of this integrityerror.)

**Comment by hancush** [comment]
this continues to recur, though i'm not sure why – when i set up the import locally (because the raw and new tables are cleared every 15 minutes by the cron imports on the server), i did not see two versions of this bill in the raw table, only the correct one. i also don't see an outdated file cached in the downloads directory on the server. so it's a bit perplexing where the duplicate is coming from, for now...

**Comment by hancush** [comment]
yay, it looks like removing the outdated bills solved the problem.

**Comment by reginafcompton** [comment]
@hancush - I ran `import_data --update_since='2018-10-10'` on the staging server without fail. I'll kick-off a rebuilding of the index, this afternoon.

**Comment by reginafcompton** [comment]
Same for the production server!
