### ISSUE TITLE
Align styles with council.nyc.gov

### ISSUE THREAD

**Issue by derekeder** [datamade/nyc-council-councilmatic#36]
We will want this site to look the same as council.nyc.gov:

<img width="1278" alt="screen shot 2017-11-27 at 12 28 17 pm" src="https://user-images.githubusercontent.com/919583/33282528-dbb51038-d3a0-11e7-96cf-4680bf05dcc2.png">

We can handle this a few ways:
* copy the header/footer & styles to match
* setup Councilmatic to work in an iframe that is embedded on one of their pages. we will still have to use the same fonts and colors. also, iframes will make hyperlinking difficult

**Comment by reginafcompton** [comment]
We've got a nice "mirror image" of the NYC gov site. Closing!
