### ISSUE TITLE
Investigate duplicate memberships

### ISSUE THREAD

**Issue by hancush** [datamade/nyc-council-councilmatic#46]
Some were apparently not resolved by #29

**Comment by hancush** [comment]
Deleted a dozen memberships where the role was an empty string: `Membership.objects.filter(organization__jurisdiction__name='New York City').filter(role='').delete()`

**Comment by reginafcompton** [comment]
@hancush - we've sorted this out by now, correct? If so, let's close!

**Comment by hancush** [comment]
Yes!!!
