### ISSUE TITLE
Legislation type SLR should be capitalized in facets

### ISSUE THREAD

**Issue by fgregg** [datamade/nyc-council-councilmatic#57]
![screenshot-2017-12-11 nyc councilmatic](https://user-images.githubusercontent.com/536941/33853251-f0e26022-de82-11e7-86e6-4ba9f3d1b387.png)

**Comment by reginafcompton** [comment]
This change allows for indexing that preserves cases: https://github.com/datamade/nyc-council-councilmatic/pull/73/files#diff-5cc31f9f594978a570b3432e9098bc6d
