### ISSUE TITLE
If i click to event from main page there's a "back to meetings" link but I don't comve from the meetings

### ISSUE THREAD

**Issue by fgregg** [datamade/nyc-council-councilmatic#60]
1. get rid of the link
2. have the link called "Meetings"
3. have the link say the right Back to X

![screenshot-2017-12-11 nyc councilmatic 2](https://user-images.githubusercontent.com/536941/33853447-9a222f14-de83-11e7-9978-ca5ac06d7d7b.png)

**Comment by reginafcompton** [comment]
This is a django-councilmatic issue. I made a small change to accommodate suggestion No. 2: https://github.com/datamade/django-councilmatic/commit/7b29900cd9ceb81b66fc4cd21523bb001cb9721b

I think better solution would be suggestion number 3, time permitting. I'll move this issue to the correct repo.
