### ISSUE TITLE
Attachments are missing from this bill page

### ISSUE THREAD

**Issue by fgregg** [datamade/nyc-council-councilmatic#61]
https://nyc-council-staging.datamade.us/legislation/lu-831-2017/

**Comment by hancush** [comment]
I just scraped this matter locally, and both attachments came with it. Looks like the bill was last updated in OCD at 9 some-odd UTC, but the attachments were last modified in Legistar at 17 some-odd. This should resolve when we turn the cron job back on and bills are updated (we turned it off to run the full scrape).

**Comment by reginafcompton** [comment]
I see attachments for this bill following our recent scrape. 

Most bills have attachments, as expected:
https://nyc-council-staging.datamade.us/legislation/int-1721-2017/
https://nyc-council-staging.datamade.us/legislation/int-1376-2016/
https://nyc-council-staging.datamade.us/legislation/int-1403-2016/
