### ISSUE TITLE
Name is awful hard to read

### ISSUE THREAD

**Issue by fgregg** [datamade/nyc-council-councilmatic#62]
The "name" of a bill is grey, in small font, on a white background. It's hard for these aging eyes to read.

https://nyc-council-staging.datamade.us/legislation/int-1786-2017/

**Comment by reginafcompton** [comment]
This change should appear across councilmatics. I've darkened the color of our `text-muted` CSS property, and removed the small tag: https://github.com/datamade/django-councilmatic/commit/7924ef17ab2b577d977fe74a85ebde4840b7c4f3
