### ISSUE TITLE
Are we purposefully not showing sponsor information?

### ISSUE THREAD

**Issue by fgregg** [datamade/nyc-council-councilmatic#64]
https://nyc-council-staging.datamade.us/legislation/int-1786-2017/

**Comment by reginafcompton** [comment]
The logic for bill sponsorships follows:

[Data scraped from Legistar API](https://github.com/opencivicdata/python-legistar-scraper/blob/master/legistar/bills.py#L309)....[NYC scraper](https://github.com/opencivicdata/scrapers-us-municipal/blob/master/nyc/bills.py#L143)
[Data imported Councilmatic](https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/management/commands/import_data.py#L1218)
[Data rendered in templates](https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/templates/councilmatic_core/legislation.html#L85
)

It looks like we [did not scrape the sponsors for this particular bill](https://ocd.datamade.us/ocd-bill/a223c7fc-eae2-40df-9908-1acad58af939/). The matter has a LastModifiedUtc of `2017-12-11T17:46:18.09`, and the sponsor has a LastModifiedUtc of `2017-12-06T18:32:27.85`. It seems like we could have missed this bill, given the irregularity of our scrapes these last days. @hancush - does that seem reasonsible?

N.B. Many bills do have sponsorships: 
https://nyc-council-staging.datamade.us/legislation/t-2017-6565/
https://nyc-council-staging.datamade.us/legislation/t-2017-5727/
https://nyc-council-staging.datamade.us/legislation/t-2017-5867/
https://nyc-council-staging.datamade.us/legislation/t-2016-4004/

**Comment by hancush** [comment]
We've had the cron turned off the past two days, so it's definitely possible we're just behind.

**Comment by reginafcompton** [comment]
@hancush - the bill in question does not have[ `sponsorships` in the OCD API,](https://ocd.datamade.us/ocd-bill/a223c7fc-eae2-40df-9908-1acad58af939/) though I see a [sponsor in the Legistar API](https://webapi.legistar.com/v1/nyc/matters/58580/sponsors/?token=). Can you look into this on the scraper-side?

**Comment by hancush** [comment]
This should take care of it. https://github.com/opencivicdata/python-legistar-scraper/pull/63

**Comment by hancush** [comment]
Unfortunately, I think it also means a big scrape (again).

**Comment by reginafcompton** [comment]
[OCD API](https://ocd.datamade.us/ocd-bill/a223c7fc-eae2-40df-9908-1acad58af939/) and [Councilmatic site](https://nyc-council-staging.datamade.us/legislation/int-1786-2017/) now have sponsors
