### ISSUE TITLE
Are we purposefully not showing bill text?

### ISSUE THREAD

**Issue by fgregg** [datamade/nyc-council-councilmatic#65]
https://nyc-council-staging.datamade.us/legislation/int-1786-2017/

**Comment by hancush** [comment]
The text is where we expect in both the [Legistar API](https://webapi.legistar.com/v1/nyc/matters/58580/texts/60785) and [OCD API](https://ocd.datamade.us/ocd-bill/a223c7fc-eae2-40df-9908-1acad58af939/), so looks like a data import or template error.

**Comment by reginafcompton** [comment]
I see bill text for this (and many others) after running a data import. 

`django-councilmatic` renders the bill text, but only provided an "abstract." See: [Import logic](https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/management/commands/import_data.py#L948), and [template logic](https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/templates/councilmatic_core/legislation.html#L68). So, this description should be missing, only if the bill does not have an abstract, e.g., https://ocd.datamade.us/ocd-bill/1a1e2abb-7b7a-4d09-ad71-89e8396382f7/

Closing.
