### ISSUE TITLE
Is this city council member really only on a single committee

### ISSUE THREAD

**Issue by fgregg** [datamade/nyc-council-councilmatic#67]
https://nyc-council-staging.datamade.us/person/corey-d-johnson-b377aefa3cfe/?view=committees

**Comment by reginafcompton** [comment]
No, he is on more than one committee: https://ocd.datamade.us/ocd-person/b824a25d-5a30-4c5e-9f9b-b377aefa3cfe/

The NYC Councilmatic settings settings [need to reflect the use of "Member" for committee roles](https://github.com/opencivicdata/scrapers-us-municipal/blob/master/nyc/people.py#L157).
