### ISSUE TITLE
Events schemas shoudl resolve to our site not legistar

### ISSUE THREAD

**Issue by fgregg** [datamade/nyc-council-councilmatic#69]
https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fnyc-council-staging.datamade.us%2Fevent%2Fcommittee-on-education-9c6f4e323984%2F

**Comment by reginafcompton** [comment]
Resolves to our site: https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fnyc-council-staging.datamade.us%2Fevent%2Fsubcommittee-on-zoning-and-franchises-65dbcac74bb8%2F
