### ISSUE TITLE
We need an image for Adrienne Adams

### ISSUE THREAD

**Issue by fgregg** [datamade/nyc-council-councilmatic#70]
https://nyc-council-staging.datamade.us/person/adrienne-e-adams-bc3b0acdf47f/

**Comment by hancush** [comment]
So it looks like we have an image for her [in the OCD API](https://ocd.datamade.us/ocd-person/8022908a-76da-454e-bd39-bc3b0acdf47f/). And the URL for said image is in the `nyc-council-councilmatic` database on the staging server. Could this be a display issue, @reginafcompton?

**Comment by reginafcompton** [comment]
We needed to manually run `collectstatic`, since these images do not reside in version control and thus do not participate in the codedeploy process (which execute `collectstatic` with a deployment).
