### ISSUE TITLE
Schema data for people should resovle (in full urls) to our site

### ISSUE THREAD

**Issue by fgregg** [datamade/nyc-council-councilmatic#71]
https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fnyc-council-staging.datamade.us%2Fperson%2Frosie-mendez-6aaf05a98863%2F

**Comment by reginafcompton** [comment]
URL resolves to our site: https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fnyc-council-staging.datamade.us%2Fevent%2Fsubcommittee-on-zoning-and-franchises-65dbcac74bb8%2F
