### ISSUE TITLE
Start by faceting bill search by current session

### ISSUE THREAD

**Issue by fgregg** [datamade/nyc-council-councilmatic#72]
Given the volume of legislation, I would suggest starting, by default to facet the current legislation by current session.

**Comment by reginafcompton** [comment]
I added a facets filter for years. A couple thoughts:

I'd prefer that it order numerically, rather than lexicographically, but I do not see that option in for SearchQuerySets: http://django-haystack.readthedocs.io/en/latest/faceting.html#configuring-facet-behaviour

**Comment by reginafcompton** [comment]
Opened up a related issue #94
