### ISSUE TITLE
This piece of leg has a sponsor but we are not showing the sponsor

### ISSUE THREAD

**Issue by fgregg** [datamade/nyc-council-councilmatic#85]
https://nyc-council-staging.datamade.us/legislation/res-1762-2017/

vs

http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=3291266&GUID=BED0EFD6-0DCB-422F-9130-55167DBDB3FB

**Comment by reginafcompton** [comment]
The `sponsorships` array for this bill is empty on the [OCD API](https://ocd.datamade.us/ocd-bill/1179378e-2cef-4cc1-9be2-2059bcb4b1eb/). @hancush - can you take a look at why the scrape misses sponsorships for this bill (and possibly others)? Related to #64.

**Comment by hancush** [comment]
This should take care of this, too https://github.com/opencivicdata/python-legistar-scraper/pull/63

**Comment by reginafcompton** [comment]
[OCD API](https://ocd.datamade.us/ocd-bill/1179378e-2cef-4cc1-9be2-2059bcb4b1eb/) and [Councilmatic site](https://nyc-council-staging.datamade.us/legislation/res-1762-2017/) both have sponsors
