### ISSUE TITLE
copy edits to Rita Allen Foundation attribution on /about page

### ISSUE THREAD

**Issue by davidmooreppf** [datamade/nyc-council-councilmatic#91]
Copy edits for [about](https://nyc-council-staging.datamade.us/about/), from Rita Allen. 

1. Correct spelling of “provided” (current page has “provied”)

2. Only the text “Rita Allen Foundation” should link to their site (not “the”)

3. Please use current boilerplate language (You can leave off the last sentence if you’d like): 
“Funding for this project was provided by the Rita Allen Foundation, which invests in transformative ideas in their earliest stages to leverage their growth and promote breakthrough solutions to significant problems. It enables early-career biomedical scholars to do pioneering research, seeds innovative approaches to fostering informed civic engagement, and develops knowledge and networks to build the effectiveness of the philanthropic sector. Throughout its work, the Foundation embraces collaboration, creativity, learning and leadership.”

Thanks Regina & al.

**Comment by reginafcompton** [comment]
Added here: http://127.0.0.1:8000/about/#credits
