### ISSUE TITLE
Why are some bills missing tags on person detail? 

### ISSUE THREAD

**Issue by reginafcompton** [datamade/nyc-council-councilmatic#97]
(1) Should these bills have tags?
(2) If not, do not show the tag icon.

<img width="1225" alt="screen shot 2017-12-18 at 10 25 50 am" src="https://user-images.githubusercontent.com/13078679/34116371-0a0afab8-e3de-11e7-897b-4b11ef083690.png">

**Comment by reginafcompton** [comment]
Solutions

(1) DELETE THESE BILLS FROM OCD and COUNCILMATIC DB
Some of the bills without tags do not appear in Legistar, but they do have an entry in OCD API. 

**[Example of Chin](http://127.0.0.1:8000/person/margaret-s-chin-4a52c935e159/)**
Land Use Call-Up 2017-6766
[OCD API](https://ocd.datamade.us/ocd-bill/56e739ee-f27c-4665-991f-ca6297093119)

Land Use Call-Up 2017-5950
[OCD API](https://ocd.datamade.us/ocd-bill/56e739ee-f27c-4665-991f-ca6297093119)

I filtered for these bills on Chin's Legistar page - with no results: http://legistar.council.nyc.gov/PersonDetail.aspx?ID=42514&GUID=D275DF50-6FAE-446D-B1E7-8AE61BC1C0B8&Search=

Note: I did find other versions of this bill, when [searching for its text in the Legistar web interface](http://legistar.council.nyc.gov/Legislation.aspx). I suspect the tag-less bills are ones that NYC created in error, we scraped them, and then a NYC admin removed them. If so, we need to manually remove them from our databases.

(2) WE DO NOT HAVE ENOUGH LOGIC FOR CREATING BILL TOPICS
Tags are populated in this template: https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/templates/partials/legislation_item.html#L26
However, we do not have enough logic for generating tags: https://github.com/datamade/django-councilmatic/blob/master/councilmatic_core/models.py#L277

**Comment by hancush** [comment]
It seems to me that NYC does a lot more altering/deleting of data than we're used to. Maybe we should escalate the priority of handling this [shoring up this known weakness of the data importers](https://github.com/opencivicdata/pupa/issues/295).

**Comment by reginafcompton** [comment]
I opened an issue to add "topics" to Bills: https://github.com/datamade/nyc-council-councilmatic/issues/121

@hancush - I think can safely delete those two bills on M. Chin's detail page. I am happy to do it, unless you have an argument against it. And definitely, yes, let's push to get started on that Pupa issue.

**Comment by reginafcompton** [comment]
Person detail has tags, now. 

But I am now seeing some oddness with the items in the Legislation search tags (which I believe point to "pseudo-topics"...which we do not consistently index in Solr). I'll open a separate issue for this, and close this one.
