### ISSUE TITLE
Message about current legislative session on search page is now inaccurate

### ISSUE THREAD

**Issue by fgregg** [datamade/nyc-council-councilmatic#98]
![screenshot-2017-12-18 nyc councilmatic](https://user-images.githubusercontent.com/536941/34117062-1817a0aa-e3e0-11e7-97c8-53084c1cefe8.png)

**Comment by reginafcompton** [comment]
I think we could simplify the message to say: "We'd be happy to help you find what you're looking for! Contact us."

(It's returning 0 results currently, because I still need to build the Solr index.)
